---

# 2. DET Pod
apiVersion: v1
kind: Pod
metadata:
  name: yolo-det
  labels:
    app: yolo
spec:
  schedulerName: volcano
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - gpu-orin2
            - gpu-orin3
  restartPolicy: Never
  containers:
    - name: yolo-gpu
      image: ultralytics/ultralytics:latest-jetson-jetpack6
      securityContext: {privileged: true}
      command: ["/bin/bash", "-c"]
      args:
        - |
          cd /mnt/yolo
          python3 -c "from ultralytics import YOLO; model = YOLO('models/yolo11n.engine'); model.predict(source='data/coco_src', imgsz=640, device=0, save=True, project='runs', name='det')"
          sleep 3600
      resources: {limits: {nvidia.com/gpu: 1}}
      volumeMounts:
        - name: yolo-shared
          mountPath: /mnt/yolo
  volumes:
    - name: yolo-shared
      persistentVolumeClaim: {claimName: yolo-shared-pvc}

